services:
    admin.client:
        class: App\Admin\ClientAdmin
        arguments: [~, App\Entity\Client, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: client, label: menu.client, label_translator_strategy: sonata.admin.label.strategy.noop, on_top: true }
        public: true

    admin.account:
        class: App\Admin\AccountAdmin
        arguments: [~, App\Entity\Account, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: account, label: menu.account, label_translator_strategy: sonata.admin.label.strategy.noop, on_top: true }
        public: true
        calls:
            - [setPasswordEncoder, ['@security.user_password_encoder.generic']]

    admin.movement:
        class: App\Admin\MovementAdmin
        arguments: [~, App\Entity\Movement, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: movement, label: menu.movement, label_translator_strategy: sonata.admin.label.strategy.noop, on_top: true }
        public: true
