sonata_admin:
    title: 'Cash Machine Admin'
    options:
        title_mode: single_text
    templates:
        layout: 'admin/layout.html.twig'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            client:
                label: menu.client
                label_catalogue: messages
                icon: '<i class="fa fa-user"></i>'
            sonata_user:
                label_catalogue: SonataUserBundle
                icon: '<i class="fa fa-users"></i>'

    security:
        handler: sonata.admin.security.handler.role
    persist_filters: true
    assets:
        extra_stylesheets:
            - 'bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-blue.min.css'
            - 'admin/css/custom.css'
        remove_stylesheets:
            - 'bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css'
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
